### ISSUE TITLE
Compatibility with the strictInjectionParameters flag 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [AmadeusITGroup/tansu#3]
Right now applications using the `strictInjectionParameters` flag will fail to compile with ngx-tansu due to the following:
* stores are marked as using "Angular features" (`@Injectable` and `ngOnDestroy`);
* stores have a constructor with a parametrised type (`constructor(private _value: T) {}`, see.:  https://github.com/AmadeusITGroup/ngx-tansu/blob/eb3869964f3b846ff45439d6a218a350a17a31db/src/index.ts#L139)

We are giving the Angular compiler contradicting messages here: on one had we say that it is "fit for DI" but then supply a type T that can't be resolved by DI. 

Not sure what is the best way of progressing here, but one way would be to drop any Angular specific constructs from the store base classes.

**Comment by divdavem** [comment]
I think we can close this issue now that we have removed the `@Injectable` decorator in #25
